FOOD_CATALOG = [
    {
        "name": "불고기 덮밥",
        "description": "든든한 단짠 밸런스로 점심이나 저녁에 실패 없는 한 그릇 메뉴입니다.",
        "tags": ["한식", "밥", "고기", "든든함", "집밥"],
        "moods": ["comfort", "reward", "focus"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["소고기", "양파", "간장", "밥"],
        "trend_keywords": ["직장인 점심", "집밥"],
    },
    {
        "name": "마라 크림 파스타",
        "description": "매콤함과 부드러움을 같이 챙기는 요즘형 퓨전 메뉴입니다.",
        "tags": ["양식", "면", "매운 음식", "트렌디", "크림"],
        "moods": ["reward", "adventure", "stress"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "spicy",
        "ingredients": ["파스타면", "우유", "고추기름", "베이컨"],
        "trend_keywords": ["마라", "꾸덕파스타"],
    },
    {
        "name": "연어 포케볼",
        "description": "가볍지만 단백질은 챙기고 싶은 날에 맞는 산뜻한 선택입니다.",
        "tags": ["헬시", "해산물", "샐러드", "가벼움", "다이어트"],
        "moods": ["light", "focus", "refresh"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["연어", "아보카도", "현미밥", "채소"],
        "trend_keywords": ["헬시플레이트", "포케"],
    },
    {
        "name": "김치찌개 정식",
        "description": "따뜻하고 진한 국물이 필요한 날에 가장 안정적인 선택입니다.",
        "tags": ["한식", "국물", "매운 음식", "따뜻함", "집밥"],
        "moods": ["comfort", "stress", "tired"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "spicy",
        "ingredients": ["김치", "두부", "돼지고기", "대파"],
        "trend_keywords": ["집밥", "국물요리"],
    },
    {
        "name": "계란볶음밥",
        "description": "냉장고 재료를 빠르게 활용할 수 있는 실전형 메뉴입니다.",
        "tags": ["중식", "밥", "간단요리", "가성비", "냉장고파먹기"],
        "moods": ["focus", "tired", "late"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "mild",
        "ingredients": ["계란", "밥", "대파", "햄"],
        "trend_keywords": ["초간단 레시피", "냉장고파먹기"],
    },
    {
        "name": "떡볶이 플래터",
        "description": "기분 전환이 필요할 때 확실하게 만족감을 주는 분식 조합입니다.",
        "tags": ["분식", "매운 음식", "간식", "트렌디", "스트레스해소"],
        "moods": ["reward", "stress", "fun"],
        "meal_times": ["lunch", "dinner", "late-night"],
        "spicy": "spicy",
        "ingredients": ["떡", "어묵", "고추장", "계란"],
        "trend_keywords": ["분식", "떡볶이"],
    },
    {
        "name": "닭가슴살 또띠아랩",
        "description": "바쁜 일정 사이에도 가볍게 챙기기 좋은 한 손 식사입니다.",
        "tags": ["헬시", "간편식", "단백질", "다이어트", "가벼움"],
        "moods": ["focus", "light", "refresh"],
        "meal_times": ["breakfast", "lunch"],
        "spicy": "mild",
        "ingredients": ["또띠아", "닭가슴살", "양상추", "소스"],
        "trend_keywords": ["프로틴밀", "간편식"],
    },
    {
        "name": "버섯 된장 파스타",
        "description": "익숙한 된장 풍미에 감칠맛을 더한 색다른 집밥 파스타입니다.",
        "tags": ["퓨전", "면", "집밥", "감칠맛", "따뜻함"],
        "moods": ["comfort", "adventure", "rainy"],
        "meal_times": ["lunch", "dinner"],
        "spicy": "mild",
        "ingredients": ["버섯", "된장", "파스타면", "마늘"],
        "trend_keywords": ["한식퓨전", "감칠맛"],
    },
]

FASHION_CATALOG = [
    {
        "name": "미니멀 셋업 룩",
        "description": "정돈된 실루엣으로 출근과 약속을 모두 커버하는 데일리 코디입니다.",
        "styles": ["미니멀", "포멀"],
        "colors": ["블랙", "네이비", "그레이", "화이트"],
        "personal_colors": ["winter cool", "summer cool"],
        "temp_min": 10,
        "temp_max": 22,
        "conditions": ["clear", "cloudy"],
        "trend_keywords": ["셋업", "미니멀룩"],
    },
    {
        "name": "크림 니트 레이어드",
        "description": "부드러운 톤으로 차분하고 포근한 인상을 주는 조합입니다.",
        "styles": ["미니멀", "캐주얼"],
        "colors": ["크림", "베이지", "아이보리"],
        "personal_colors": ["spring warm", "autumn warm"],
        "temp_min": 5,
        "temp_max": 18,
        "conditions": ["clear", "cloudy", "windy"],
        "trend_keywords": ["니트레이어드", "톤온톤"],
    },
    {
        "name": "스트릿 윈드브레이커",
        "description": "활동량이 많고 가볍게 포인트를 주고 싶은 날에 적합합니다.",
        "styles": ["스트릿", "스포티"],
        "colors": ["카키", "블랙", "네온", "블루"],
        "personal_colors": ["spring warm", "winter cool"],
        "temp_min": 12,
        "temp_max": 24,
        "conditions": ["windy", "cloudy", "clear"],
        "trend_keywords": ["고프코어", "윈드브레이커"],
    },
    {
        "name": "모노톤 데님 믹스",
        "description": "캐주얼하지만 단정해 보여서 캠퍼스와 카페 일정에 잘 어울립니다.",
        "styles": ["캐주얼", "미니멀"],
        "colors": ["블루", "화이트", "그레이"],
        "personal_colors": ["summer cool", "winter cool"],
        "temp_min": 14,
        "temp_max": 26,
        "conditions": ["clear", "cloudy"],
        "trend_keywords": ["데님룩", "클린핏"],
    },
    {
        "name": "코지 라운지웨어",
        "description": "집중해서 일하거나 집에서 쉬는 날 편안함을 우선하는 선택입니다.",
        "styles": ["캐주얼", "홈웨어"],
        "colors": ["그레이", "크림", "핑크", "민트"],
        "personal_colors": ["spring warm", "summer cool"],
        "temp_min": 18,
        "temp_max": 30,
        "conditions": ["rainy", "cloudy", "clear"],
        "trend_keywords": ["꾸안꾸", "라운지웨어"],
    },
    {
        "name": "포멀 블레이저 포인트",
        "description": "프레젠테이션이나 중요한 일정에 신뢰감을 주는 조합입니다.",
        "styles": ["포멀", "미니멀"],
        "colors": ["네이비", "블랙", "와인", "화이트"],
        "personal_colors": ["winter cool", "autumn warm"],
        "temp_min": 8,
        "temp_max": 22,
        "conditions": ["clear", "cloudy"],
        "trend_keywords": ["블레이저룩", "오피스코어"],
    },
    {
        "name": "애슬레저 트레이닝 셋",
        "description": "가볍게 몸을 움직이거나 이동이 많은 날에 적합한 실전형 코디입니다.",
        "styles": ["스포티", "캐주얼"],
        "colors": ["블랙", "차콜", "블루", "화이트"],
        "personal_colors": ["summer cool", "winter cool"],
        "temp_min": 15,
        "temp_max": 28,
        "conditions": ["clear", "cloudy", "windy"],
        "trend_keywords": ["애슬레저", "러닝룩"],
    },
]

CONTENT_CATALOG = [
    {
        "name": "한 회 완결형 힐링 웹툰",
        "description": "짧은 시간 안에 기분 전환이 가능한 가벼운 웹툰 타입입니다.",
        "genres": ["로맨스", "일상", "힐링"],
        "platforms": ["웹툰"],
        "moods": ["light", "comfort", "refresh"],
        "trend_keywords": ["힐링웹툰", "짧은콘텐츠"],
    },
    {
        "name": "몰입형 범죄 스릴러 영화",
        "description": "한 번에 몰입해서 보고 싶은 저녁 시간에 잘 맞는 선택입니다.",
        "genres": ["스릴러", "범죄", "미스터리"],
        "platforms": ["영화"],
        "moods": ["focus", "dark", "reward"],
        "trend_keywords": ["범죄스릴러", "반전영화"],
    },
    {
        "name": "20분 생산성 유튜브",
        "description": "의욕을 끌어올리고 싶을 때 짧게 보기 좋은 자기계발형 콘텐츠입니다.",
        "genres": ["자기계발", "브이로그", "정보"],
        "platforms": ["유튜브"],
        "moods": ["focus", "refresh", "light"],
        "trend_keywords": ["생산성", "루틴영상"],
    },
    {
        "name": "감성 로맨틱 코미디 드라마",
        "description": "하루를 부드럽게 마무리하고 싶을 때 안정적으로 즐길 수 있습니다.",
        "genres": ["로맨스", "코미디", "드라마"],
        "platforms": ["드라마"],
        "moods": ["comfort", "light", "reward"],
        "trend_keywords": ["로코", "감성드라마"],
    },
    {
        "name": "판타지 세계관 웹툰",
        "description": "현실 분리가 필요할 때 몰입감을 주는 장르형 선택입니다.",
        "genres": ["판타지", "액션", "모험"],
        "platforms": ["웹툰"],
        "moods": ["adventure", "reward", "focus"],
        "trend_keywords": ["이세계", "판타지웹툰"],
    },
    {
        "name": "현장감 있는 여행 브이로그",
        "description": "밖에 나가기 어렵더라도 간접 여행 기분을 낼 수 있는 콘텐츠입니다.",
        "genres": ["여행", "브이로그", "힐링"],
        "platforms": ["유튜브"],
        "moods": ["refresh", "light", "comfort"],
        "trend_keywords": ["여행브이로그", "로컬맛집"],
    },
    {
        "name": "짧고 강한 SF 미드",
        "description": "빠르게 다음 화를 누르게 만드는 텐션 높은 선택지입니다.",
        "genres": ["SF", "스릴러", "드라마"],
        "platforms": ["드라마"],
        "moods": ["focus", "dark", "adventure"],
        "trend_keywords": ["SF드라마", "떡밥회수"],
    },
    {
        "name": "마음 편한 요리 영화",
        "description": "먹고 싶은 기분과 따뜻한 분위기를 동시에 채워주는 타입입니다.",
        "genres": ["드라마", "힐링", "음식"],
        "platforms": ["영화"],
        "moods": ["comfort", "light", "foodie"],
        "trend_keywords": ["푸드필름", "힐링무비"],
    },
]

ACTIVITY_CATALOG = [
    {
        "name": "카페 저널링",
        "description": "혼자서도 집중감 있게 하루를 정리할 수 있는 저자극 활동입니다.",
        "indoor_outdoor": "indoor",
        "energy": "low",
        "social": "solo",
        "budget": "medium",
        "trend_keywords": ["감성카페", "기록습관"],
    },
    {
        "name": "한강 산책 루프",
        "description": "가볍게 몸을 움직이며 머리를 환기시키기 좋은 대표적인 리셋 활동입니다.",
        "indoor_outdoor": "outdoor",
        "energy": "medium",
        "social": "either",
        "budget": "low",
        "trend_keywords": ["산책", "러닝크루"],
    },
    {
        "name": "집중형 보드게임 나이트",
        "description": "친구와 함께 실내에서 텐션 있게 시간을 보내기 좋은 선택입니다.",
        "indoor_outdoor": "indoor",
        "energy": "medium",
        "social": "group",
        "budget": "medium",
        "trend_keywords": ["보드게임", "집모임"],
    },
    {
        "name": "실내 클라이밍 체험",
        "description": "몸을 쓰면서도 성취감을 빠르게 느낄 수 있는 액티브한 활동입니다.",
        "indoor_outdoor": "indoor",
        "energy": "high",
        "social": "either",
        "budget": "medium",
        "trend_keywords": ["클라이밍", "액티비티"],
    },
    {
        "name": "동네 전시 산책",
        "description": "실내외를 오가며 새로운 자극을 얻고 싶은 날에 어울립니다.",
        "indoor_outdoor": "mixed",
        "energy": "medium",
        "social": "either",
        "budget": "medium",
        "trend_keywords": ["전시회", "문화생활"],
    },
    {
        "name": "홈트 20분 챌린지",
        "description": "시간이 많지 않아도 컨디션을 끌어올릴 수 있는 짧은 루틴입니다.",
        "indoor_outdoor": "indoor",
        "energy": "high",
        "social": "solo",
        "budget": "low",
        "trend_keywords": ["홈트", "짧은운동"],
    },
    {
        "name": "친구와 신상 맛집 탐방",
        "description": "주말이나 퇴근 후에 대화와 먹는 즐거움을 함께 챙길 수 있습니다.",
        "indoor_outdoor": "outdoor",
        "energy": "medium",
        "social": "group",
        "budget": "high",
        "trend_keywords": ["신상맛집", "핫플"],
    },
    {
        "name": "방 정리 + 플레이리스트 업데이트",
        "description": "적은 예산으로 분위기를 전환하고 성취감도 남기는 실내 활동입니다.",
        "indoor_outdoor": "indoor",
        "energy": "low",
        "social": "solo",
        "budget": "low",
        "trend_keywords": ["방꾸미기", "플리추천"],
    },
]
