services:
  web:
    build: .
    container_name: ai-academic-validator-web
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: ai_academic_validator
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:7
    container_name: ai-academic-validator-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
